### ISSUE TITLE
README.md - Linux install

### ISSUE THREAD

**Issue by Its-Kenta** [Lancelotbronner/swift-raylib#1]
Hey, amazing work here! Great to see another up to date Raylib binding for Swift! Have you updated the raylibs binding list on the official repo yet?

Just wanted to point out a small mistake in the readme for installing Raylib on Linux:

**Linux - AUR**
```sh
apt-get install raylib
```

This is wrong.
AUR is Arch User Repository which would be used with AUR helpers like yay or paru. IIRC Raylib can be downloaded by simply running `sudo pacman -S raylib` as it's in the `extra` repository.

IMO I would advise sending users off to Raylibs official guides on installing Raylib on their system?

Once again, great work!

**Comment by Lancelotbronner** [comment]
I believe I took this from the raylib guide but I might be wrong, in any case directing users to the official guide is a much better solution, I'll remove that section and put more emphasis on the link.
